name: flutter_application_1
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mongo_dart: ^0.10.0
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  multi_select_flutter: ^4.1.3
  responsive_sizer: ^3.3.0
  http: ^1.2.0
  flutter_google_maps_webservices: ^1.1.1
  fast_contacts: ^3.1.3
  permission_handler: ^11.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  typed_data: ^1.3.2
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  get: ^4.6.6
  sentry_flutter: ^7.15.0
  connection_notifier: ^2.0.1
  # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  # - assets/images/bg.jpg
  # - assets/icons/cd.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
